FROM oisupport/perl-bashbrew

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends curl; \
	rm -rf /var/lib/apt/lists/*

COPY .remote.pl /usr/local/bin/remote.pl
ENTRYPOINT ["remote.pl"]
